import type {
  WebAppResource,
  DeploymentSourceConfig,
  DeploymentEntry,
  DeploymentSlot,
  FtpsCredentials,
} from '../types';

const now = Date.now();
const hours = (h: number) => h * 60 * 60 * 1000;
const minutes = (m: number) => m * 60 * 1000;

export const webApp: WebAppResource = {
  name: 'nl-testwebapp-1',
  resourceGroup: 'rg-web-prod-eastus',
  subscriptionName: 'Visual Studio Enterprise',
  subscriptionId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  location: 'East US',
  status: 'Running',
  defaultHostName: 'nl-testwebapp-1.azurewebsites.net',
  appServicePlan: 'asp-prod-eastus-p1v3',
  operatingSystem: 'Linux',
  runtimeStack: 'Node 22-LTS',
  publishingModel: 'Code',
  healthCheckPath: '/api/health',
};

export const deploymentSource: DeploymentSourceConfig = {
  type: 'github',
  buildProvider: 'githubActions',
  githubOrg: 'NicL9923',
  githubRepo: 'my-node-app',
  githubBranch: 'main',
  workflowFileName: 'azure-deploy.yml',
  repoUrl: 'https://github.com/NicL9923/my-node-app',
  branch: 'main',
};

export const deploymentHistory: DeploymentEntry[] = [
  {
    id: 'dep-001',
    timestamp: new Date(now - minutes(12)).toISOString(),
    author: 'NicL9923',
    status: 'InProgress',
    message: 'Build and deploy in progress...',
    commitId: 'a3f8b2c',
    commitMessage: 'feat: add real-time notification websocket endpoint',
    branch: 'main',
    targetSlot: 'production',
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '  Syncing repository: NicL9923/my-node-app',
      '  Working directory: /home/runner/work/my-node-app',
      '▶ Run actions/setup-node@v4',
      '  Node.js version 22.x installed',
      '▶ Run npm ci',
      '  npm warn deprecated inflight@1.0.6',
      '  added 847 packages in 23s',
      '▶ Run npm run build',
      '  > my-node-app@2.1.0 build',
      '  > tsc && vite build',
      '  Building for production...',
    ],
    phases: [
      { name: 'Checkout', status: 'complete', startedAt: new Date(now - minutes(12)).toISOString(), completedAt: new Date(now - minutes(11)).toISOString() },
      { name: 'Install', status: 'complete', startedAt: new Date(now - minutes(11)).toISOString(), completedAt: new Date(now - minutes(8)).toISOString() },
      { name: 'Build', status: 'active', startedAt: new Date(now - minutes(8)).toISOString() },
      { name: 'Test', status: 'pending' },
      { name: 'Deploy', status: 'pending' },
    ],
  },
  {
    id: 'dep-002',
    timestamp: new Date(now - hours(1.5)).toISOString(),
    author: 'NicL9923',
    status: 'Success',
    message: 'Deployment successful',
    commitId: 'e7d4a91',
    commitMessage: 'fix: resolve memory leak in connection pool manager',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 94,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '  Syncing repository: NicL9923/my-node-app',
      '▶ Run actions/setup-node@v4',
      '  Node.js version 22.x installed',
      '▶ Run npm ci',
      '  added 847 packages in 21s',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Run npm test',
      '  Tests: 142 passed, 0 failed',
      '▶ Deploy to Azure Web App',
      '  Deployment successful. Site: nl-testwebapp-1.azurewebsites.net',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'complete' },
      { name: 'Deploy', status: 'complete' },
    ],
  },
  {
    id: 'dep-003',
    timestamp: new Date(now - hours(4)).toISOString(),
    author: 'NicL9923',
    status: 'Success',
    message: 'Deployment successful',
    commitId: 'b1c2d3e',
    commitMessage: 'chore: upgrade express to 5.1.0 and update middleware chain',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 112,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run actions/setup-node@v4',
      '▶ Run npm ci',
      '  added 851 packages in 24s',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Run npm test',
      '  Tests: 142 passed, 0 failed',
      '▶ Deploy to Azure Web App',
      '  Deployment successful.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'complete' },
      { name: 'Deploy', status: 'complete' },
    ],
  },
  {
    id: 'dep-004',
    timestamp: new Date(now - hours(8)).toISOString(),
    author: 'dependabot[bot]',
    status: 'Success',
    message: 'Deployment successful',
    commitId: 'c4d5e6f',
    commitMessage: 'chore(deps): bump axios from 1.7.2 to 1.7.9',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 78,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run npm ci',
      '  added 847 packages in 19s',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Run npm test',
      '  Tests: 142 passed, 0 failed',
      '▶ Deploy to Azure Web App',
      '  Deployment successful.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'complete' },
      { name: 'Deploy', status: 'complete' },
    ],
  },
  {
    id: 'dep-005',
    timestamp: new Date(now - hours(23)).toISOString(),
    author: 'NicL9923',
    status: 'Failed',
    message: 'Build failed — TypeScript compilation errors',
    commitId: 'f7a8b9c',
    commitMessage: 'feat: add user preference caching layer',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 42,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run actions/setup-node@v4',
      '▶ Run npm ci',
      '  added 847 packages in 20s',
      '▶ Run npm run build',
      '  src/cache/PreferenceCache.ts(24,11): error TS2322: Type string is not assignable to type number',
      '  src/cache/PreferenceCache.ts(31,5): error TS2345: Argument of type CacheEntry is not assignable',
      '  Build failed with 2 errors',
      '❌ Process completed with exit code 1.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'failed' },
      { name: 'Test', status: 'pending' },
      { name: 'Deploy', status: 'pending' },
    ],
  },
  {
    id: 'dep-006',
    timestamp: new Date(now - hours(26)).toISOString(),
    author: 'NicL9923',
    status: 'Success',
    message: 'Deployment successful',
    commitId: 'd0e1f2a',
    commitMessage: 'refactor: extract auth middleware into separate module',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 101,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run npm ci',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Run npm test',
      '  Tests: 138 passed, 0 failed',
      '▶ Deploy to Azure Web App',
      '  Deployment successful.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'complete' },
      { name: 'Deploy', status: 'complete' },
    ],
  },
  {
    id: 'dep-007',
    timestamp: new Date(now - hours(48)).toISOString(),
    author: 'NicL9923',
    status: 'Success',
    message: 'Deployment successful',
    commitId: 'a2b3c4d',
    commitMessage: 'feat: implement rate limiting for public API endpoints',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 135,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run npm ci',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Run npm test',
      '  Tests: 136 passed, 0 failed',
      '▶ Deploy to Azure Web App',
      '  Deployment successful.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'complete' },
      { name: 'Deploy', status: 'complete' },
    ],
  },
  {
    id: 'dep-008',
    timestamp: new Date(now - hours(72)).toISOString(),
    author: 'NicL9923',
    status: 'Canceled',
    message: 'Deployment canceled by user',
    commitId: 'e5f6a7b',
    commitMessage: 'wip: experimental graphql resolver — not ready',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 18,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run npm ci',
      '  added 847 packages in 20s',
      '⚠ Workflow canceled by user.',
    ],
  },
  {
    id: 'dep-009',
    timestamp: new Date(now - hours(96)).toISOString(),
    author: 'NicL9923',
    status: 'Success',
    message: 'Deployment successful',
    commitId: 'c8d9e0f',
    commitMessage: 'fix: correct timezone handling in scheduled job runner',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 88,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run npm ci',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Run npm test',
      '  Tests: 134 passed, 0 failed',
      '▶ Deploy to Azure Web App',
      '  Deployment successful.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'complete' },
      { name: 'Deploy', status: 'complete' },
    ],
  },
  {
    id: 'dep-010',
    timestamp: new Date(now - hours(120)).toISOString(),
    author: 'NicL9923',
    status: 'Failed',
    message: 'Deployment failed — health check timeout',
    commitId: '1a2b3c4',
    commitMessage: 'feat: add prometheus metrics endpoint',
    branch: 'main',
    targetSlot: 'production',
    durationSeconds: 178,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run npm ci',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Run npm test',
      '  Tests: 132 passed, 0 failed',
      '▶ Deploy to Azure Web App',
      '  Deploying package...',
      '  Waiting for site to start...',
      '  ❌ Health check failed: /api/health returned 503 after 300s',
      '  Deployment failed.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'complete' },
      { name: 'Deploy', status: 'failed' },
    ],
  },
];

const stagingLastDeploy: DeploymentEntry = {
  id: 'dep-stg-001',
  timestamp: new Date(now - hours(2)).toISOString(),
  author: 'NicL9923',
  status: 'Success',
  message: 'Staging deployment successful',
  commitId: 'a3f8b2c',
  commitMessage: 'feat: add real-time notification websocket endpoint',
  branch: 'main',
  targetSlot: 'staging',
  durationSeconds: 97,
  sourceType: 'github',
  buildLogs: [
    '▶ Run actions/checkout@v4',
    '▶ Run npm ci',
    '▶ Run npm run build',
    '  Build completed successfully',
    '▶ Deploy to staging slot',
    '  Deployment successful.',
  ],
  phases: [
    { name: 'Checkout', status: 'complete' },
    { name: 'Install', status: 'complete' },
    { name: 'Build', status: 'complete' },
    { name: 'Test', status: 'complete' },
    { name: 'Deploy', status: 'complete' },
  ],
};

export const stagingDeploymentHistory: DeploymentEntry[] = [
  {
    id: 'dep-stg-002',
    timestamp: new Date(now - hours(6)).toISOString(),
    author: 'NicL9923',
    status: 'Success',
    message: 'Staging deployment successful',
    commitId: 'b1c2d3e',
    commitMessage: 'chore: upgrade express to 5.1.0 and update middleware chain',
    branch: 'main',
    targetSlot: 'staging',
    durationSeconds: 105,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run npm ci',
      '  added 851 packages in 22s',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Deploy to staging slot',
      '  Deployment successful.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'complete' },
      { name: 'Deploy', status: 'complete' },
    ],
  },
  {
    id: 'dep-stg-003',
    timestamp: new Date(now - minutes(45)).toISOString(),
    author: 'NicL9923',
    status: 'InProgress',
    message: 'Staging build and deploy in progress...',
    commitId: 'e7d4a91',
    commitMessage: 'fix: resolve memory leak in connection pool manager',
    branch: 'main',
    targetSlot: 'staging',
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '  Syncing repository: NicL9923/my-node-app',
      '▶ Run actions/setup-node@v4',
      '  Node.js version 22.x installed',
      '▶ Run npm ci',
      '  added 847 packages in 21s',
      '▶ Run npm run build',
      '  Building for staging...',
    ],
    phases: [
      { name: 'Checkout', status: 'complete', startedAt: new Date(now - minutes(45)).toISOString(), completedAt: new Date(now - minutes(44)).toISOString() },
      { name: 'Install', status: 'complete', startedAt: new Date(now - minutes(44)).toISOString(), completedAt: new Date(now - minutes(41)).toISOString() },
      { name: 'Build', status: 'active', startedAt: new Date(now - minutes(41)).toISOString() },
      { name: 'Test', status: 'pending' },
      { name: 'Deploy', status: 'pending' },
    ],
  },
  {
    id: 'dep-stg-004',
    timestamp: new Date(now - hours(28)).toISOString(),
    author: 'NicL9923',
    status: 'Failed',
    message: 'Staging deployment failed — test suite failures',
    commitId: 'f7a8b9c',
    commitMessage: 'feat: add user preference caching layer',
    branch: 'main',
    targetSlot: 'staging',
    durationSeconds: 67,
    sourceType: 'github',
    buildLogs: [
      '▶ Run actions/checkout@v4',
      '▶ Run npm ci',
      '  added 847 packages in 20s',
      '▶ Run npm run build',
      '  Build completed successfully',
      '▶ Run npm test',
      '  FAIL src/cache/PreferenceCache.test.ts',
      '  Tests: 3 failed, 139 passed',
      '❌ Process completed with exit code 1.',
    ],
    phases: [
      { name: 'Checkout', status: 'complete' },
      { name: 'Install', status: 'complete' },
      { name: 'Build', status: 'complete' },
      { name: 'Test', status: 'failed' },
      { name: 'Deploy', status: 'pending' },
    ],
  },
];

export const allDeployments: DeploymentEntry[] = [
  ...deploymentHistory,
  ...stagingDeploymentHistory,
  stagingLastDeploy,
].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

export const deploymentSlots: DeploymentSlot[] = [
  {
    name: 'production',
    isProduction: true,
    status: 'Running',
    lastDeployment: deploymentHistory[1],
    trafficPercentage: 100,
    url: 'https://nl-testwebapp-1.azurewebsites.net',
    runtimeStack: 'Node 22-LTS',
    appSettings: [
      { name: 'NODE_ENV', value: 'production', isSlotSetting: true },
      { name: 'DATABASE_URL', value: 'mongodb+srv://prod-cluster.mongodb.net/app', isSlotSetting: false },
      { name: 'REDIS_URL', value: 'redis://prod-cache.redis.cache.windows.net:6380', isSlotSetting: false },
      { name: 'LOG_LEVEL', value: 'warn', isSlotSetting: true },
      { name: 'FEATURE_FLAG_NOTIFICATIONS', value: 'true', isSlotSetting: false },
    ],
  },
  {
    name: 'staging',
    isProduction: false,
    status: 'Running',
    lastDeployment: stagingLastDeploy,
    trafficPercentage: 0,
    url: 'https://nl-testwebapp-1-staging.azurewebsites.net',
    runtimeStack: 'Node 22-LTS',
    appSettings: [
      { name: 'NODE_ENV', value: 'staging', isSlotSetting: true },
      { name: 'DATABASE_URL', value: 'mongodb+srv://staging-cluster.mongodb.net/app', isSlotSetting: false },
      { name: 'REDIS_URL', value: 'redis://staging-cache.redis.cache.windows.net:6380', isSlotSetting: false },
      { name: 'LOG_LEVEL', value: 'debug', isSlotSetting: true },
      { name: 'FEATURE_FLAG_NOTIFICATIONS', value: 'true', isSlotSetting: false },
    ],
  },
];

export const ftpsCredentials: FtpsCredentials = {
  endpoint: 'ftps://waws-prod-blu-123.ftp.azurewebsites.windows.net/site/wwwroot',
  appScopeUsername: 'nl-testwebapp-1\\$nl-testwebapp-1',
  appScopePassword: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  userScopeUsername: 'nicl9923',
  userScopePassword: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  isEnabled: false,
};

export const availableOrgs: string[] = ['NicL9923', 'microsoft', 'Azure'];

export const availableRepos: Record<string, string[]> = {
  NicL9923: ['my-node-app', 'portfolio-site', 'api-gateway', 'infra-templates'],
  microsoft: ['vscode', 'TypeScript', 'fluentui', 'playwright'],
  Azure: ['azure-sdk-for-js', 'azure-cli', 'bicep', 'azure-functions-host'],
};

export const availableBranches: string[] = ['main', 'develop', 'feature/new-ui', 'hotfix/deploy-fix'];
